# Generated by Django 4.2 on 2023-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_api_url",
                    models.CharField(max_length=50, verbose_name="Spotify API Url"),
                ),
                (
                    "spotify_client_id",
                    models.CharField(max_length=50, verbose_name="Spotify Client ID"),
                ),
                (
                    "spotify_client_secret_key",
                    models.CharField(
                        max_length=50, verbose_name="Spotify Client Secret Key"
                    ),
                ),
                (
                    "spotify_api_scope",
                    models.CharField(max_length=800, verbose_name="Spotify API Scope"),
                ),
                (
                    "spotify_redirect_uri",
                    models.CharField(
                        max_length=100, verbose_name="Spotify Redirect Uri"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
    ]
